### ISSUE TITLE
gotutorial tech writer

### ISSUE THREAD

**Issue by iamqizhao** [grpc/grpc-common#131]
@LisaFC 

Hi Lisa,

It would be highly appreciated if you can help take a look at grpc/grpc-common/go/gotutorial.go. Thanks!

**Comment by LisaFC** [comment]
About to send a PR - quick question first:
- What's the difference between SendAndClose() (used in the client-side streaming method on the server) and CloseSend() (used in the bidirectional streaming method on the client)?

**Comment by iamqizhao** [comment]
Thanks.

On Fri, Feb 27, 2015 at 8:41 AM, LisaFC <notifications@github.com> wrote:

> About to send a PR - quick question first:
>
>    - What's the difference between SendAndClose() (used in the
>    client-side streaming method on the server) and CloseSend() (used in the
>    bidirectional streaming method on the client)?
>
> CloseSend is simply WritesDone in C++, which signals sending is done from
its side.  SendAndClose()  sends the last proto message and return (no
further message can be sent after this call.).
