### ISSUE TITLE
C++ Helloworld example uses CreateChannelDeprecated

### ISSUE THREAD

**Issue by nbeckman** [grpc/grpc-common#133]
I'm looking at this example
https://github.com/grpc/grpc-common/blob/master/cpp/helloworld/greeter_client.cc#L83

And it uses the CreateChannelDeprecated function. Is there a newer, non-deprecated function that could be used? It might be more appropriate for an example that will likely get copy and pasted lots of times.

Thanks!

**Comment by ctiller** [comment]
Hey - we're in the process of updating that API. The update is in grpc/grpc#835 if you want to take a peek. Hopefully the change lands in the coming week or two.

We'll definitely update examples once that happens.

**Comment by nbeckman** [comment]
Hi Craig, sounds good! Thanks. 
I'll keep an eye on the PR and maybe check back again after it has gotten in.

**Comment by sahlberg** [comment]
This can be close now that https://github.com/grpc/grpc-common/pull/151
is merged ?

**Comment by nbeckman** [comment]
Yep, thanks!
