### ISSUE TITLE
Some useful information about Markdown

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc-common#15]
Markdown syntax highlighting has support for Protocol Buffers. [This file](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) has a list of every supported language. You can get this by putting [`protobuf`](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L2330) in the code fence.

Custom link anchors (`<a name="something"></a>`) are not always necessary. All headers already have these, with the full text of the header slugified to make the anchor name. To get the anchor link for a specific header on a live Markdown file on GitHub, hovering over the header will display a link icon (:link:) that links to that header.

GitHub has a live Markdown editor on the website. To get to it, visit the file directly, then click the edit link (pencil icon) in the upper right corner. This allows you to preview the edit before submitting it.

For a good reference, the [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) has pretty much all of the important information. [This page](http://daringfireball.net/projects/markdown/syntax) is also helpful for more technical syntax information.

**Comment by philips** [comment]
Is this an issue? Seems like it can be closed.
