### ISSUE TITLE
Add header to distiguish between grpc streams and others

### ISSUE THREAD

**Issue by acasajus** [grpc/grpc-common#152]
It would be nice if there was an explicit and required way in the grpc streams to distinguish them from others (for instance normal web traffic). This way a single port could serve a web page and the services via grpc. Options that come to mind are: 
 
 - Either add a header to all grpc stream (grpc-stream or grpc-version or something like that)
 - Use a special method (like grpc) in the :method header

Cheers :beers:

**Comment by louiscryan** [comment]
We handle this by mandating a Content-Type of "application/grpc". Is that insufficient

**Comment by acasajus** [comment]
Oops. I missed that in
https://github.com/grpc/grpc-common/blob/master/PROTOCOL-HTTP2.md

Cheers,
