### ISSUE TITLE
Make it possible to use a Java nano client to test a Java server

### ISSUE THREAD

**Issue by boosh** [grpc/grpc-common#157]
I want to implement a Java nano client at the same time as a Java server. So I've set up a multi-project gradle repo with the subprojects 'client', 'server' and 'shared':

- the 'client' subproject contains a Java nano client
- the 'server' subproject contains a Java server
- the 'shared' subproject just contains my .proto file.

I've created a test class in my 'server' subproject called TestServer. This instantiates and starts an instance of the server, and also starts an instance of a client. It then uses the client to test the API and assert the responses are as expected.

Initially I created an ApiClient class in the 'server' subproject, and used that in my TestServer as the client. This worked. Because it was using the non-nano generated code, I used the builders to build protobuf datatypes, just like the server was doing.

But, when I created a gradle testCompile dependency between my client and server subprojects, so the 'server' depended on the 'client', things stopped working. The problem is that the nano code doesn't use builders for creating the protobuf datatypes, but instead uses accessors, i.e.:

```
// Creating a User in the nano client:
User user = new User();
user.username = "the username";

// Creating a User in the server:
User user = User.newBuilder().setUsername("the username").build();
// the accessor style used by java nano is not permitted on the server because the 
// constructors and fields are private.
```

The package name of the generated code is the same for both the client and the server, but has different implementations. So when I include my nano client in tests on in my 'server' subproject, the class loader can load the client, but when it instantiates a 'User' object in the nano client it loads the one from the 'server' subproject which uses the builder pattern. If I change the package name of the client generated code, I get NotImplemented exceptions raised by the server, presumably because the types don't match.

It'd be really useful to be able to develop both in parallel, and to use the nano client to test the server. The way to fix this seems to be for the non-nano objects to have public constructors and accessors as well as supporting builders. 

Alternatively is there any way I can force my client jar to only load classes from within that jar itself, and not to load them from the 'server' subproject instead when it's being used from within the 'server' subproject?

**Comment by madongfly** [comment]
I believe the current proto/grpc generator generates nano code with an extra `nano` directory by default, so you should be able to use both `com.foo.bar.Message` and `com.foo.bar.nano.Message` in the same time.

I'm closing this, feel free to reopen it if you meet any problem.
