### ISSUE TITLE
How to use curl as client

### ISSUE THREAD

**Issue by emaxin** [grpc/grpc-common#158]
After build grpc-common/cpp/helloworld, I use curl to send request like this:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 curl -v -X POST -d '{"name":"world"}'  http://127.0.0.1:50051/SayHello -H "Content-Type:application/grpc+json"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

in greeter_client side it prints out:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
* About to connect() to 127.0.0.1 port 50051 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 50051 (#0)
> POST /SayHello HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:50051
> Accept: */*
> Content-Type:application/grpc+json
> Content-Length: 16
> 
* upload completely sent off: 16 out of 16 bytes
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

in greeter_server side it prints out:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
E0315 18:34:43.347566027   14660 chttp2_transport.c:1570] Connect string mismatch: expected 'R' (82) got 'O' (79) at byte 1
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I have not got "Hello world" message.

Could some body help me find what is wrong?

**Comment by jhump** [comment]
@emaxin, `curl`, unfortunately, won't be this easy to use. You've specified a content-type (as required) of "application/grpc+json" but the actual data you pass is just plain ol' "application/json".

See here for the format of the payload: https://github.com/grpc/grpc-common/blob/master/PROTOCOL-HTTP2.md#requests. In particular, look at the *Delimited Message* item as that is describes the request's data payload.

To support streaming, each "chunk" (or single element in a stream) must be placed in an envelope that describes the chunk's size and encoding. This is a binary protocol, so it's possible to do with `curl`, but certainly not simple.

**Comment by emaxin** [comment]
Thanks jhump for explaining in detail ! 
Sorry I'am new to grpc. Does that mean I can only use grpc wrapper call as client other than using some build-in function call of certain language to access to grpc server? Could you please give me some sugestion?

**Comment by jhump** [comment]
@emaxin, I think it would be better to use the client library instead of re-building the protocol details on top of simpler primitives. It may be worth filing a new issue to implement something like `grpc-curl`, to potentially make troubleshooting a server easier.

**Comment by emaxin** [comment]
@jhump I see and follow your sugestion. thanks
