### ISSUE TITLE
run server and then client in document

### ISSUE THREAD

**Issue by vnitinv** [grpc/grpc-common#161]
https://github.com/grpc/grpc-common/tree/master/python/helloworld#the-server

should be referenced before 

https://github.com/grpc/grpc-common/tree/master/python/helloworld#the-client

programmer should take care of running server first and then client. But if we just follow this doc blindly end up running client without server and hence client errors out.

Hence it would be better to change the order.

**Comment by nathanielmanistaatgoogle** [comment]
Closing; [the current documentation](http://www.grpc.io/docs/tutorials/basic/python.html) does proceed in the desired order.
