### ISSUE TITLE
protobuf v3.0.0-alpha-2 is in Homebrew now

### ISSUE THREAD

**Issue by paperstreet** [grpc/grpc-common#162]
Not sure if you're interested in mentioning this in the docs, but protobuf v3.0.0-alpha-2 is now in [Homebrew](http://brew.sh/), a popular OS X package manager. It makes it a lot easier to install from source.
    brew update && brew install --devel protobuf

**Comment by louiscryan** [comment]
cool. we're working on a comprehensive fix to this problem for folks but you might want to submit a PR on the protobuf repo showing folks how to use this.

@jcanizales

**Comment by jcanizales** [comment]
Awesomeness!

What took me longest to figure out in order to install it was the it's necessary to add
```bash
export CPATH=/usr/local/include:$CPATH
export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
```
to your environment. I've only _used_ Homebrew, but I hope it can modify a user's `.bash_profile`?

@tbetbetbe

**Comment by tbetbetbe** [comment]
FYI: there is a grpc homebrew repo: grpc/grpc-homebrew#11

Until gRPC reaches 1.0 and protobuf v3 leave alpha, we'll be maintaining a formula there along with a helper script to simplify installation.

I will close this issue as we tracking homebrew packaging at grpc/grpc#1210

**Comment by timini** [comment]
nice :)

**Comment by afshinm** [comment]
brew install --devel protobuf --force
