### ISSUE TITLE
Python helloworld client: "RPC write not accepted"

### ISSUE THREAD

**Issue by Juzley** [grpc/grpc-common#163]
I'm trying to run the python hello world examples on a fresh ubuntu 14.04 install, but running into an issue with the client not being able to send RPCs to the server. Here's the log:

~/grpc-common/python/helloworld$ python greeter_server.py  &
[1] 26449
~/grpc-common/python/helloworld$ netstat -a | grep 50051
tcp6       0      0 [::]:50051              [::]:*                  LISTEN
~/grpc-common/python/helloworld$ python greeter_client.py 
ERROR:root:RPC write not accepted! Event: (Event(kind=<Kind.WRITE_ACCEPTED: <object object at 0xb75304c8>>, tag=UUID('33a32e3c-c9ea-4594-9294-27b56d424110'), write_accepted=False, complete_accepted=None, service_acceptance=None, bytes=None, status=None),)
Traceback (most recent call last):
  File "greeter_client.py", line 44, in <module>
    run()
  File "greeter_client.py", line 39, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'), _TIMEOUT_SECONDS)
  File "/usr/local/lib/python2.7/dist-packages/grpc/early_adopter/_reexport.py", line 158, in __call__
    self._underlying, request, timeout)
  File "/usr/local/lib/python2.7/dist-packages/grpc/early_adopter/_reexport.py", line 113, in _call_reexporting_errors
    raise _reexport_error(e)
grpc.early_adopter.exceptions.ExpirationError
D0318 10:04:52.261256665   26463 iomgr.c:107] Waiting for 1 iomgr objects to be destroyed
D0318 10:05:02.262263114   26463 iomgr.c:121] Failed to free 1 iomgr objects before shutdown deadline: memory leaks are likely

**Comment by nathanielmanistaatgoogle** [comment]
Yep - the Python API has undergone some changes in the last two weeks and I'm not sure that the example code has stayed current. Look for a fix in the next few days.

**Comment by nathanielmanistaatgoogle** [comment]
Closing; the `early_adopter` API was removed some time ago.
