### ISSUE TITLE
Python examples use proto2

### ISSUE THREAD

**Issue by LisaFC** [grpc/grpc-common#172]
Only just spotted this - is there a reason for this that I missed somewhere? I'm currently updating the protocol buffers docs and warning people off using gRPC with proto2 unless they absolutely have to because of compatibility issues with proto3.

**Comment by LisaFC** [comment]
Actually, I tell a lie, the Hello World is proto3 but the Route Guide seems to be proto2, unless there are multiple versions of the proto in the repo.

**Comment by nathanielmanistaatgoogle** [comment]
I am completely agnostic on the matter and happy for explicit-support-for-one-particular-proto-version to be decided by someone else.

If cross-language policy favors proto3 I'm perfectly happy to see Python updated to conform to that. :-)

**Comment by LisaFC** [comment]
@tbetbetbe, we should change this to proto3, yes?

**Comment by tbetbetbe** [comment]
yes please!

On 31 March 2015 at 11:03, LisaFC <notifications@github.com> wrote:

> @tbetbetbe <https://github.com/tbetbetbe>, we should change this to
> proto3, yes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grpc/grpc-common/issues/172#issuecomment-88190789>.
>



-- 
This email may be confidential or privileged.  If you received this
communication by mistake, please don't forward it to anyone else (it may
contain confidential or privileged information), please erase all copies of
it, including all attachments, and please let the sender know it went to
the wrong person. Thanks.

**Comment by LisaFC** [comment]
Had just changed the .proto in the route_guide directory to proto3 in my version of the repo, then realized that what in fact we should do is just have the Python example use the .proto in the protos directory....

**Comment by LisaFC** [comment]
Ok, see #174 for update.
