### ISSUE TITLE
Add a simple sample demonstrating gRPC python authentication

### ISSUE THREAD

**Issue by tbetbetbe** [grpc/grpc-common#183]
Update [the auth document](https://github.com/grpc/grpc-common/blob/master/grpc-auth-support.md) with a python snippet, similar to the C++, Ruby and Node snippets.

**Comment by tbetbetbe** [comment]
@nathanielmanistaatgoogle, @soltanmm 
It'd be nice to get this completed before #245

Please ping @LisaFC once this is done, so that she can update the official [auth documentation](http://www.grpc.io/docs/guides/auth.html)

**Comment by murgatroid99** [comment]
After discussing this with Tim, we decided that the timing of this change is independent of #245.

**Comment by tbetbetbe** [comment]
@soltanmm ping.  These docs would unblock GoogleCloudPlatform/gcloud-python#872
