### ISSUE TITLE
The Ruby helloworld client and server crash on startup

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc-common#191]
In the Ruby helloworld example, both the client and server fail with the error

```
/usr/local/google/home/mlumish/grpc/src/ruby/lib/grpc/generic/bidi_call.rb:38:in `<class:BidiCall>': uninitialized constant GRPC::Core::CallOps (NameError)
```

**Comment by tbetbetbe** [comment]
FYI: That's because we have not updated the instructions for how to install gRPC.
We did not build a deb for release 0.6.0, and instead are relying on a new packaging system for developers
That should be published in the next few days, and this bug will be resolved then.

**Comment by murgatroid99** [comment]
I was actually building against gRPC HEAD, not a deb package.
