### ISSUE TITLE
C# examples and Nuget packages?

### ISSUE THREAD

**Issue by zeliard** [grpc/grpc-common#196]
Are there any csharp grpc examples (helloworld, route_guide, or so) which use protobuf 3.x?
If so, could you upload those examples into this grpc-common repo?

And, is there any plan to register grpc.core prereleases to nuget.org?

**Comment by jtattermusch** [comment]
We are planning to add the helloworld example for C# to grpc-common very soon. It will use a gRPC C# nuget package that we will publish along with it, so stay tuned.

regarding protobufs:
We are planning to use the C# protobufs from https://github.com/google/protobuf/tree/csharp. They will support proto3 in the future (but currently they only support proto2 syntax).

**Comment by zeliard** [comment]
@jtattermusch cool! I'm looking forward to it!

**Comment by zeliard** [comment]
Although a new c# greeter example was uploaded,
I couldn't able to retrieve grpc nuget packages yet. 

FYI: VS2013 error messages ---------------
Error	1	NuGet Package restore failed for project Greeter: Unable to find version '0.5.0' of package 'Grpc'..		0
Error	2	NuGet Package restore failed for project GreeterServer: Unable to find version '0.5.0' of package 'Grpc'..		0
Error	3	NuGet Package restore failed for project GreeterClient: Unable to find version '0.5.0' of package 'Grpc.Core'..		0

**Comment by jtattermusch** [comment]
Yes, the packages weren't published yet (as gRPC C# alpha also wasn't officially released as alpha yet). 
To obtain the packages, please see #1623.

**Comment by zeliard** [comment]
Thanks @jtattermusch 
https://github.com/grpc/grpc/issues/1623
