### ISSUE TITLE
Need C# route guide tutorial and example

### ISSUE THREAD

**Issue by LisaFC** [grpc/grpc-common#211]

**Comment by zeliard** [comment]
@jtattermusch uploaded that
 https://github.com/grpc/grpc-common/tree/master/csharp/route_guide

**Comment by LisaFC** [comment]
BTW, @jtattermusch - is this ready to go into grpc.io (I can make any improvements to the text, but just want to make sure there aren't going to be any major changes to the code)? I can copy it over to the doc repo if so.

**Comment by jtattermusch** [comment]
Yes, I am not planning any major changes. Please go ahead and copy it over to the doc repo.
