### ISSUE TITLE
Tool for manually sending requests to gRPC servers

### ISSUE THREAD

**Issue by hjfreyer** [grpc/grpc-common#216]
gRPC needs browser and/or CLI based tools for manually sending requests to servers, for testing and fiddling-about purposes.

**Comment by hjfreyer** [comment]
Oops, probably the wrong repo. Opened an issue in the main one: https://github.com/grpc/grpc/issues/1776

**Comment by yang-g** [comment]
Please look at grpc_cli at https://github.com/grpc/grpc/blob/master/test/cpp/util/grpc_cli.cc
It is very simple but can do the simple rpcs.
