### ISSUE TITLE
How to use client certificate?

### ISSUE THREAD

**Issue by tthn** [grpc/grpc-common#217]
here is the client-side code:
```cpp
  grpc::SslCredentialsOptions ssl_opts;
  ssl_opts.pem_root_certs = get_file_content("cert.pem");
  ssl_opts.pem_private_key = get_file_content("client-cert/key.pem");
  ssl_opts.pem_cert_chain = get_file_content("client-cert/cert.pem");
```
here is the server-side code:
```cpp
  grpc::SslServerCredentialsOptions ssl_opts;
  grpc::SslServerCredentialsOptions::PemKeyCertPair p = {
    get_file_content("key.pem"), get_file_content("cert.pem")
  };
  ssl_opts.pem_key_cert_pairs.push_back(p);
  ssl_opts.pem_root_certs = get_file_content("client-cert/cert.pem");
  auto creds = SslServerCredentials(ssl_opts);
```
====
it seems that whether the client set the key/perm or not, it will always perform the RPC call successfully.

**Comment by jboeuf** [comment]
Yes this is an issue that I'm aware of. I think that a fix will require an API change on the server SSL creds as I could see a server accepting both authenticated and non-authenticated clients. 
When the upcoming server auth context is checked-in (https://github.com/grpc/grpc/pull/1672), along with the C++ wrapped version of it, the application will be able to have access to the client peer identity (or lack thereof) and make a decision based on this.
I agree however, that it would be nicer to configure that at the SSL level and will add that to my TODO list.

**Comment by tthn** [comment]
cool, appreciate
