### ISSUE TITLE
The installation script does not work

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc-common#229]
I tried to run the installation script using the provided command `curl -fsSL https://goo.gl/getgrpc | bash -` and I got the following output:

```
openssl is already installed
Warning: Already tapped!
Error: No available formula for google-protobuf
Searching formulae...
Searching taps...
Error: No available formula for grpc
Searching formulae...
Searching taps...
```

**Comment by tbetbetbe** [comment]
What were you trying to do ?
- had you previously either run the script of installed grpc using homebrew ?
- Try running `brew update`, then try the script again and let me know if that works.
- it may be that we need to run brew update as part of the script

**Comment by murgatroid99** [comment]
I think I have previously installed grpc using homebrew, but I'm not sure. I tried running `brew update`, and got this output:

```
error: Your local changes to the following files would be overwritten by merge:
	Library/.rubocop.yml
...
	Libra
error: The following untracked working tree files would be overwritten by merge:
	Library/Aliases/blazegraph
...
	Library/Homebrew/utils/fork.rb
Please move or remove them before you can merge.
Aborting
Error: Failure while executing: git pull -q origin refs/heads/master:refs/remotes/origin/master
```

With a lot more filenames where I put ellipses.

**Comment by murgatroid99** [comment]
I was able to fix the previous error using the instructions [here](http://stackoverflow.com/questions/17868956/homebrew-update-fail-please-commit-your-changes-or-stash-them-before-you-can)

**Comment by tbetbetbe** [comment]
Closing this.  This looks like the issue was that you had unresolved local changes in homebrew repo
