### ISSUE TITLE
Add PHP auth example to grpc-common/grpc-auth-support.md

### ISSUE THREAD

**Issue by tbetbetbe** [grpc/grpc-common#249]
[grpc-auth-support.md](https://github.com/grpc/grpc-common/blob/master/grpc-auth-support.md) should have a paragraph add to it showing how to authenticate against a google service, cf grpc/grpc-common@4e7b4ad42da58ae4ef7f2282ab0af11fc7c1073a

It should use the same auth code as is used in the auth interop tests.

**Comment by tbetbetbe** [comment]
This should be completed before #245

**Comment by stanley-cheung** [comment]
Got it

**Comment by tbetbetbe** [comment]
Thanks - please ping @LisaFC once this is done, so that she can update the official [auth documentation](http://www.grpc.io/docs/guides/auth.html)

**Comment by murgatroid99** [comment]
After discussing this with Tim, we decided that the timing of this change is independent of #245.
