### ISSUE TITLE
helloworld greeter_client.cpp crashes

### ISSUE THREAD

**Issue by satish-baliga** [grpc/grpc-common#270]
Access violation, stack trace:
grpc::FillMetadataArray  Line 67
grpc::CallOpSendInitialMetadata::SendInitialMetadata  Line 167
grpc::BlockingUnaryCall Line 64
helloworld::Greeter::Stub::SayHello Line 30

The server runs OK: "Server listening on 0.0.0.0:50051"

Built with static libraries, debug mode on VS 2013, Windows 8.1.

**Comment by larsonmpdx** [comment]
try and see if it's related to compiler option _USE_32BIT_TIME_T, see
https://github.com/grpc/grpc/issues/2595

**Comment by satish-baliga** [comment]
Resolved. Thanks for the quick reply. For future reference:
<img width="361" alt="capture" src="https://cloud.githubusercontent.com/assets/3314682/9309297/5075048e-4526-11e5-9547-9cd58e6cea70.PNG">
Recompiled my client, server & .pb.cc generation project(s) with _USE_32BIT_TIME_T preprocessor definition.
