### ISSUE TITLE
Move examples to grpc-* repos

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc-common#282]

**Comment by philips** [comment]
When will this be rebuilt on grpc.io? There are problems with the grpc.io Go examples: http://www.grpc.io/docs/installation/go.html

**Comment by LisaFC** [comment]
We're actually moving all the quickstart/installation guides out of grpc.io in the next major update, and just linking to the relevant READMEs in the relevant depot, as they are probably most useful next to the code. Grpc.io will have more substantial guides, tutorials and reference material. 

In the meantime, if this is correct (https://github.com/grpc/grpc-go/tree/master/examples) and the version on grpc.io isn't, I can just make the update myself now if you like?

**Comment by philips** [comment]
@LisaFC These are the fixes that the grpc.io page needs.

**Comment by LisaFC** [comment]
Ah, I see, the link to the helloworld.proto is broken (in fairness, it's also broken in the repo README). The repo README also tells users to get the code using

go get -u google.golang.org/grpc/examples/helloworld/greeter_client

while the grpc.io page says

go get -u github.com/grpc/grpc-go/examples/helloworld/greeter_client

- should I change the grpc.io page to match the repo one?

**Comment by philips** [comment]
@LisaFC Yes, the grpc-go repo one is correct.

**Comment by LisaFC** [comment]
Done!
