### ISSUE TITLE
put health and etc. proto files in common

### ISSUE THREAD

**Issue by dapengzhang0** [grpc/grpc-common#285]
There have been multiple health.proto files in different places with minor different option fields:

https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto
https://github.com/grpc/grpc-java/blob/master/services/src/main/proto/health.proto
https://github.com/grpc/grpc-go/blob/master/health/grpc_health_v1/health.proto

As discussed in grpc/grpc-java#1821 @ejona86 @carl-mastrangelo @buchgr @ctiller, it may be better to have a synced up version in grpc/grpc-common

**Comment by carl-mastrangelo** [comment]
+1
